# Generated by Django 5.2.3 on 2025-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/imgs/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('A', 'Aluno'), ('I', 'Instrutor'), ('ADM', 'Administrador')], default='A', max_length=3),
        ),
    ]
