# Generated by Django 5.2.3 on 2025-06-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classcourse',
            table='class_course',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table='evaluation',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='progress',
        ),
    ]
